/**
 * BrowserUp Proxy
 * BrowserUp Proxy Control API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AfterRequest model module.
 * @module BrowserUpProxyClient/model/AfterRequest
 * @version 1.0.0
 */
class AfterRequest {
    /**
     * Constructs a new <code>AfterRequest</code>.
     * @alias module:BrowserUpProxyClient/model/AfterRequest
     * @param lastAccess {String} 
     * @param eTag {String} 
     * @param hitCount {Number} 
     */
    constructor(lastAccess, eTag, hitCount) { 
        
        AfterRequest.initialize(this, lastAccess, eTag, hitCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, lastAccess, eTag, hitCount) { 
        obj['lastAccess'] = lastAccess;
        obj['eTag'] = eTag;
        obj['hitCount'] = hitCount;
    }

    /**
     * Constructs a <code>AfterRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:BrowserUpProxyClient/model/AfterRequest} obj Optional instance to populate.
     * @return {module:BrowserUpProxyClient/model/AfterRequest} The populated <code>AfterRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AfterRequest();

            if (data.hasOwnProperty('expires')) {
                obj['expires'] = ApiClient.convertToType(data['expires'], 'String');
            }
            if (data.hasOwnProperty('lastAccess')) {
                obj['lastAccess'] = ApiClient.convertToType(data['lastAccess'], 'String');
            }
            if (data.hasOwnProperty('eTag')) {
                obj['eTag'] = ApiClient.convertToType(data['eTag'], 'String');
            }
            if (data.hasOwnProperty('hitCount')) {
                obj['hitCount'] = ApiClient.convertToType(data['hitCount'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} expires
 */
AfterRequest.prototype['expires'] = undefined;

/**
 * @member {String} lastAccess
 */
AfterRequest.prototype['lastAccess'] = undefined;

/**
 * @member {String} eTag
 */
AfterRequest.prototype['eTag'] = undefined;

/**
 * @member {Number} hitCount
 */
AfterRequest.prototype['hitCount'] = undefined;

/**
 * @member {String} comment
 */
AfterRequest.prototype['comment'] = undefined;






export default AfterRequest;

