/**
 * BrowserUp Proxy
 * ___ This is the REST API for controlling the BrowserUp Proxy.  The BrowserUp Proxy is a swiss army knife for automated testing. It allows traffic capture in HAR files and manipulation.  It is also useful for Selenium/Cypress tests. ___ 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlockList model module.
 * @module BrowserUpProxyClient/model/BlockList
 * @version 1.0.0
 */
class BlockList {
    /**
     * Constructs a new <code>BlockList</code>.
     * @alias module:BrowserUpProxyClient/model/BlockList
     * @param statusCode {String} HTTP Status Code
     * @param urlPattern {String} URL Regex Pattern
     * @param httpMethodPattern {String} HTTP Method Regex Pattern
     */
    constructor(statusCode, urlPattern, httpMethodPattern) { 
        
        BlockList.initialize(this, statusCode, urlPattern, httpMethodPattern);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, statusCode, urlPattern, httpMethodPattern) { 
        obj['status_code'] = statusCode;
        obj['url_pattern'] = urlPattern;
        obj['http_method_pattern'] = httpMethodPattern;
    }

    /**
     * Constructs a <code>BlockList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:BrowserUpProxyClient/model/BlockList} obj Optional instance to populate.
     * @return {module:BrowserUpProxyClient/model/BlockList} The populated <code>BlockList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockList();

            if (data.hasOwnProperty('status_code')) {
                obj['status_code'] = ApiClient.convertToType(data['status_code'], 'String');
            }
            if (data.hasOwnProperty('url_pattern')) {
                obj['url_pattern'] = ApiClient.convertToType(data['url_pattern'], 'String');
            }
            if (data.hasOwnProperty('http_method_pattern')) {
                obj['http_method_pattern'] = ApiClient.convertToType(data['http_method_pattern'], 'String');
            }
        }
        return obj;
    }


}

/**
 * HTTP Status Code
 * @member {String} status_code
 */
BlockList.prototype['status_code'] = undefined;

/**
 * URL Regex Pattern
 * @member {String} url_pattern
 */
BlockList.prototype['url_pattern'] = undefined;

/**
 * HTTP Method Regex Pattern
 * @member {String} http_method_pattern
 */
BlockList.prototype['http_method_pattern'] = undefined;






export default BlockList;

