/**
 * BrowserUp Proxy
 * BrowserUp Proxy Control API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntryResponseContent model module.
 * @module BrowserUpProxyClient/model/EntryResponseContent
 * @version 1.0.0
 */
class EntryResponseContent {
    /**
     * Constructs a new <code>EntryResponseContent</code>.
     * @alias module:BrowserUpProxyClient/model/EntryResponseContent
     * @param size {Number} 
     * @param mimeType {String} 
     */
    constructor(size, mimeType) { 
        
        EntryResponseContent.initialize(this, size, mimeType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, size, mimeType) { 
        obj['size'] = size;
        obj['mimeType'] = mimeType;
    }

    /**
     * Constructs a <code>EntryResponseContent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:BrowserUpProxyClient/model/EntryResponseContent} obj Optional instance to populate.
     * @return {module:BrowserUpProxyClient/model/EntryResponseContent} The populated <code>EntryResponseContent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntryResponseContent();

            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('compression')) {
                obj['compression'] = ApiClient.convertToType(data['compression'], 'Number');
            }
            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('encoding')) {
                obj['encoding'] = ApiClient.convertToType(data['encoding'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} size
 */
EntryResponseContent.prototype['size'] = undefined;

/**
 * @member {Number} compression
 */
EntryResponseContent.prototype['compression'] = undefined;

/**
 * @member {String} mimeType
 */
EntryResponseContent.prototype['mimeType'] = undefined;

/**
 * @member {String} text
 */
EntryResponseContent.prototype['text'] = undefined;

/**
 * @member {String} encoding
 */
EntryResponseContent.prototype['encoding'] = undefined;

/**
 * @member {String} comment
 */
EntryResponseContent.prototype['comment'] = undefined;






export default EntryResponseContent;

