/**
 * BrowserUp Proxy
 * BrowserUp Proxy Control API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Timings model module.
 * @module BrowserUpProxyClient/model/Timings
 * @version 1.0.0
 */
class Timings {
    /**
     * Constructs a new <code>Timings</code>.
     * @alias module:BrowserUpProxyClient/model/Timings
     * @param send {Number} 
     * @param wait {Number} 
     * @param receive {Number} 
     */
    constructor(send, wait, receive) { 
        
        Timings.initialize(this, send, wait, receive);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, send, wait, receive) { 
        obj['send'] = send;
        obj['wait'] = wait;
        obj['receive'] = receive;
    }

    /**
     * Constructs a <code>Timings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:BrowserUpProxyClient/model/Timings} obj Optional instance to populate.
     * @return {module:BrowserUpProxyClient/model/Timings} The populated <code>Timings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Timings();

            if (data.hasOwnProperty('dns')) {
                obj['dns'] = ApiClient.convertToType(data['dns'], 'Number');
            }
            if (data.hasOwnProperty('connect')) {
                obj['connect'] = ApiClient.convertToType(data['connect'], 'Number');
            }
            if (data.hasOwnProperty('blocked')) {
                obj['blocked'] = ApiClient.convertToType(data['blocked'], 'Number');
            }
            if (data.hasOwnProperty('send')) {
                obj['send'] = ApiClient.convertToType(data['send'], 'Number');
            }
            if (data.hasOwnProperty('wait')) {
                obj['wait'] = ApiClient.convertToType(data['wait'], 'Number');
            }
            if (data.hasOwnProperty('receive')) {
                obj['receive'] = ApiClient.convertToType(data['receive'], 'Number');
            }
            if (data.hasOwnProperty('ssl')) {
                obj['ssl'] = ApiClient.convertToType(data['ssl'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} dns
 */
Timings.prototype['dns'] = undefined;

/**
 * @member {Number} connect
 */
Timings.prototype['connect'] = undefined;

/**
 * @member {Number} blocked
 */
Timings.prototype['blocked'] = undefined;

/**
 * @member {Number} send
 */
Timings.prototype['send'] = undefined;

/**
 * @member {Number} wait
 */
Timings.prototype['wait'] = undefined;

/**
 * @member {Number} receive
 */
Timings.prototype['receive'] = undefined;

/**
 * @member {Number} ssl
 */
Timings.prototype['ssl'] = undefined;

/**
 * @member {String} comment
 */
Timings.prototype['comment'] = undefined;






export default Timings;

