# coding: utf-8

"""
BrowserUp MitmProxy

___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___

The version of the OpenAPI document: 1.0.0
Contact: developers@browserup.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any
from typing import Optional

from pydantic import BaseModel
from pydantic import conlist
from pydantic import Field
from pydantic import StrictInt
from pydantic import StrictStr

from BrowserUpMitmProxyClient.models.har_entry_request_cookies_inner import (
    HarEntryRequestCookiesInner,
)
from BrowserUpMitmProxyClient.models.har_entry_response_content import (
    HarEntryResponseContent,
)
from BrowserUpMitmProxyClient.models.header import Header


class HarEntryResponse(BaseModel):
    """
    HarEntryResponse
    """

    status: StrictInt = Field(...)
    status_text: StrictStr = Field(..., alias="statusText")
    http_version: StrictStr = Field(..., alias="httpVersion")
    cookies: conlist(HarEntryRequestCookiesInner) = Field(...)
    headers: conlist(Header) = Field(...)
    content: HarEntryResponseContent = Field(...)
    redirect_url: StrictStr = Field(..., alias="redirectURL")
    headers_size: StrictInt = Field(..., alias="headersSize")
    body_size: StrictInt = Field(..., alias="bodySize")
    comment: Optional[StrictStr] = None
    additional_properties: dict[str, Any] = {}
    __properties = [
        "status",
        "statusText",
        "httpVersion",
        "cookies",
        "headers",
        "content",
        "redirectURL",
        "headersSize",
        "bodySize",
        "comment",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HarEntryResponse:
        """Create an instance of HarEntryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True, exclude={"additional_properties"}, exclude_none=True
        )
        # override the default output from pydantic by calling `to_dict()` of each item in cookies (list)
        _items = []
        if self.cookies:
            for _item in self.cookies:
                if _item:
                    _items.append(_item.to_dict())
            _dict["cookies"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in headers (list)
        _items = []
        if self.headers:
            for _item in self.headers:
                if _item:
                    _items.append(_item.to_dict())
            _dict["headers"] = _items
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict["content"] = self.content.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HarEntryResponse:
        """Create an instance of HarEntryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HarEntryResponse.parse_obj(obj)

        _obj = HarEntryResponse.parse_obj(
            {
                "status": obj.get("status"),
                "status_text": obj.get("statusText"),
                "http_version": obj.get("httpVersion"),
                "cookies": [
                    HarEntryRequestCookiesInner.from_dict(_item)
                    for _item in obj.get("cookies")
                ]
                if obj.get("cookies") is not None
                else None,
                "headers": [Header.from_dict(_item) for _item in obj.get("headers")]
                if obj.get("headers") is not None
                else None,
                "content": HarEntryResponseContent.from_dict(obj.get("content"))
                if obj.get("content") is not None
                else None,
                "redirect_url": obj.get("redirectURL"),
                "headers_size": obj.get("headersSize"),
                "body_size": obj.get("bodySize"),
                "comment": obj.get("comment"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
