name: 'setup'
description: 'checkout and setup uv'
inputs:
  uv-sync-args:
    description: 'Arguments for uv sync ...'
runs:
  using: "composite"
  steps:
    - uses: mhils/workflows/setup-uv@42ac4652123201e0b4646175b78b25819cf6bfaf
    - uses: mhils/workflows/uv-sync@main
      with:
        args: ${{ inputs.uv-sync-args }}
