comment: off
coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      python:
        paths:
          - "!web/"
      web:
        paths:
          - "web/"
codecov:
  notify:
    after_n_builds: 6