comment: off
coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      python:
        target: auto
        threshold: 0.1%
        paths:
          - "mitmproxy/"
          - "examples/addons/"
      web:
        target: auto
        threshold: 0.1%
        paths:
          - "web/"
