#!/bin/bash
set -e
VENV=../venv.mitmproxy

python -m virtualenv $VENV
source $VENV/bin/activate
pip install --src .. -r requirements.txt

echo ""
echo "* Created virtualenv environment in $VENV."
echo "* Installed all dependencies into the virtualenv."
echo "* Activated virtualenv environment."
