#!/usr/bin/env python

# Copyright (C) 2010  Aldo Cortesi
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys, os.path
from libmproxy import proxy, dump, utils
from libmproxy import VERSION
from optparse import OptionParser, OptionGroup


if __name__ == '__main__':
    parser = OptionParser(
                usage = "%prog [options]",
                version="%%prog %s"%VERSION,
            )
    utils.certificate_option_group(parser)
    parser.add_option(
        "-p", "--port", action="store",
        type = "int", dest="port", default=8080,
        help = "Port."
    )
    parser.add_option("-q", "--quiet",
                      action="store_true", dest="quiet",
                      help="Quiet.")
    parser.add_option("-v", "--verbose",
                      action="count", dest="verbose", default=1,
                      help="Increase verbosity. Can be passed multiple times.")
    options, args = parser.parse_args()

    if options.quiet:
        options.verbose = 0

    options.cert = os.path.expanduser(options.cert)
    options.certpath = os.path.expanduser(options.certpath)
    
    if not os.path.exists(options.cert):
        print >> sys.stderr, "Creating bogus certificate at %s"%options.cert
        utils.make_bogus_cert(options.cert)

    proxy.config = proxy.Config(
        certfile = options.cert,
        certpath = options.certpath,
        cacert   = options.cacert,
        ciphers = options.ciphers
    )
    server = proxy.ProxyServer(options.port)

    dumpopts = dump.Options(
        verbosity = options.verbose
    )
    m = dump.DumpMaster(server, dumpopts)

    if options.verbose > 0:
        print >> sys.stderr, "Running on port %s"%options.port
    m.run()
