#!/usr/bin/env python

# Copyright (C) 2010  Aldo Cortesi
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys, signal
# The unneccesary console import here is to work around a bug in pyinstaller
from libmproxy import proxy, dump, cmdline, version, console
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(usage = "%(prog)s [options] [filter]")
    parser.add_argument('--version', action='version', version=version.NAMEVERSION)
    cmdline.common_options(parser)
    parser.add_argument(
        "--keepserving",
        action="store_true", dest="keepserving", default=False,
        help="Continue serving after client playback or file read. We exit by default."
    )
    parser.add_argument('args', nargs=argparse.REMAINDER)

    options = parser.parse_args()

    if options.quiet:
        options.verbose = 0

    proxyconfig = proxy.process_proxy_options(parser, options)
    if options.no_server:
        server = proxy.DummyServer(proxyconfig)
    else:
        try:
            server = proxy.ProxyServer(proxyconfig, options.port, options.addr)
        except proxy.ProxyServerError, v:
            print >> sys.stderr, "mitmdump:", v.args[0]
            sys.exit(1)


    try:
        dumpopts = dump.Options(**cmdline.get_common_options(options))
    except cmdline.OptionException, v:
        parser.error(v.message)
    dumpopts.keepserving = options.keepserving

    if options.args:
        filt = " ".join(options.args)
    else:
        filt = None

    try:
        m = dump.DumpMaster(server, dumpopts, filt)
        def cleankill(*args, **kwargs):
            m.shutdown()
        signal.signal(signal.SIGTERM, cleankill)
        m.run()
    except dump.DumpError, e:
        print >> sys.stderr, "mitmdump:", e
        sys.exit(1)
    except KeyboardInterrupt:
        pass



