#!/usr/bin/env python
#
# Simple script showing how to read a mitmproxy dump file
#

from mitmproxy import flow
import pprint
import sys

with open(sys.argv[1], "rb") as logfile:
    freader = flow.FlowReader(logfile)
    pp = pprint.PrettyPrinter(indent=4)
    try:
        for f in freader.stream():
            print(f)
            print(f.request.host)
            pp.pprint(f.get_state())
            print("")
    except flow.FlowReadError as v:
        print "Flow file corrupted. Stopped loading."
