=begin
#BrowserUp Proxy

#BrowserUp Proxy Control API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

# Common files
require 'browserup_proxy_client/api_client'
require 'browserup_proxy_client/api_error'
require 'browserup_proxy_client/version'
require 'browserup_proxy_client/configuration'

# Models
require 'browserup_proxy_client/models/allow_list'
require 'browserup_proxy_client/models/block_list'

# APIs
require 'browserup_proxy_client/api/proxy_api'

module BrowserupProxyClient
  class << self
    # Customize default settings for the SDK using block.
    #   BrowserupProxyClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
