/*
 * BrowserUp Proxy
 * BrowserUp Proxy Control API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.browserup.proxy_client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BlockList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BlockList {
  public static final String SERIALIZED_NAME_STATUS_CODE = "statusCode";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  private String statusCode;

  public static final String SERIALIZED_NAME_URL_PATTERN = "urlPattern";
  @SerializedName(SERIALIZED_NAME_URL_PATTERN)
  private String urlPattern;

  public static final String SERIALIZED_NAME_HTTP_METHOD_PATTERN = "httpMethodPattern";
  @SerializedName(SERIALIZED_NAME_HTTP_METHOD_PATTERN)
  private String httpMethodPattern;


  public BlockList statusCode(String statusCode) {
    
    this.statusCode = statusCode;
    return this;
  }

   /**
   * HTTP Status Code
   * @return statusCode
  **/
  @ApiModelProperty(required = true, value = "HTTP Status Code")

  public String getStatusCode() {
    return statusCode;
  }


  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }


  public BlockList urlPattern(String urlPattern) {
    
    this.urlPattern = urlPattern;
    return this;
  }

   /**
   * URL Regex Pattern
   * @return urlPattern
  **/
  @ApiModelProperty(required = true, value = "URL Regex Pattern")

  public String getUrlPattern() {
    return urlPattern;
  }


  public void setUrlPattern(String urlPattern) {
    this.urlPattern = urlPattern;
  }


  public BlockList httpMethodPattern(String httpMethodPattern) {
    
    this.httpMethodPattern = httpMethodPattern;
    return this;
  }

   /**
   * HTTP Method Regex Pattern
   * @return httpMethodPattern
  **/
  @ApiModelProperty(required = true, value = "HTTP Method Regex Pattern")

  public String getHttpMethodPattern() {
    return httpMethodPattern;
  }


  public void setHttpMethodPattern(String httpMethodPattern) {
    this.httpMethodPattern = httpMethodPattern;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockList blockList = (BlockList) o;
    return Objects.equals(this.statusCode, blockList.statusCode) &&
        Objects.equals(this.urlPattern, blockList.urlPattern) &&
        Objects.equals(this.httpMethodPattern, blockList.httpMethodPattern);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusCode, urlPattern, httpMethodPattern);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockList {\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    urlPattern: ").append(toIndentedString(urlPattern)).append("\n");
    sb.append("    httpMethodPattern: ").append(toIndentedString(httpMethodPattern)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

