/*
 * BrowserUp Proxy
 * ___ This is the REST API for controlling the BrowserUp Proxy. The BrowserUp Proxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___ 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.browserup.proxy_client;

import java.util.Objects;
import java.util.Arrays;
import com.browserup.proxy_client.EntryRequest;
import com.browserup.proxy_client.EntryResponse;
import com.browserup.proxy_client.WebSocketMessage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Entry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Entry {
  public static final String SERIALIZED_NAME_PAGEREF = "pageref";
  @SerializedName(SERIALIZED_NAME_PAGEREF)
  private String pageref;

  public static final String SERIALIZED_NAME_STARTED_DATE_TIME = "startedDateTime";
  @SerializedName(SERIALIZED_NAME_STARTED_DATE_TIME)
  private String startedDateTime;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private BigDecimal time;

  public static final String SERIALIZED_NAME_REQUEST = "request";
  @SerializedName(SERIALIZED_NAME_REQUEST)
  private EntryRequest request;

  public static final String SERIALIZED_NAME_RESPONSE = "response";
  @SerializedName(SERIALIZED_NAME_RESPONSE)
  private EntryResponse response;

  public static final String SERIALIZED_NAME_CACHE = "cache";
  @SerializedName(SERIALIZED_NAME_CACHE)
  private Object cache;

  public static final String SERIALIZED_NAME_TIMINGS = "timings";
  @SerializedName(SERIALIZED_NAME_TIMINGS)
  private Object timings;

  public static final String SERIALIZED_NAME_SERVER_I_P_ADDRESS = "serverIPAddress";
  @SerializedName(SERIALIZED_NAME_SERVER_I_P_ADDRESS)
  private String serverIPAddress;

  public static final String SERIALIZED_NAME_WEB_SOCKET_MESSAGES = "_webSocketMessages";
  @SerializedName(SERIALIZED_NAME_WEB_SOCKET_MESSAGES)
  private List<WebSocketMessage> webSocketMessages = null;

  public static final String SERIALIZED_NAME_CONNECTION = "connection";
  @SerializedName(SERIALIZED_NAME_CONNECTION)
  private String connection;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;


  public Entry pageref(String pageref) {
    
    this.pageref = pageref;
    return this;
  }

   /**
   * Get pageref
   * @return pageref
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPageref() {
    return pageref;
  }


  public void setPageref(String pageref) {
    this.pageref = pageref;
  }


  public Entry startedDateTime(String startedDateTime) {
    
    this.startedDateTime = startedDateTime;
    return this;
  }

   /**
   * Get startedDateTime
   * @return startedDateTime
  **/
  @ApiModelProperty(required = true, value = "")

  public String getStartedDateTime() {
    return startedDateTime;
  }


  public void setStartedDateTime(String startedDateTime) {
    this.startedDateTime = startedDateTime;
  }


  public Entry time(BigDecimal time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * minimum: 0
   * @return time
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getTime() {
    return time;
  }


  public void setTime(BigDecimal time) {
    this.time = time;
  }


  public Entry request(EntryRequest request) {
    
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @ApiModelProperty(required = true, value = "")

  public EntryRequest getRequest() {
    return request;
  }


  public void setRequest(EntryRequest request) {
    this.request = request;
  }


  public Entry response(EntryResponse response) {
    
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  @ApiModelProperty(required = true, value = "")

  public EntryResponse getResponse() {
    return response;
  }


  public void setResponse(EntryResponse response) {
    this.response = response;
  }


  public Entry cache(Object cache) {
    
    this.cache = cache;
    return this;
  }

   /**
   * Get cache
   * @return cache
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getCache() {
    return cache;
  }


  public void setCache(Object cache) {
    this.cache = cache;
  }


  public Entry timings(Object timings) {
    
    this.timings = timings;
    return this;
  }

   /**
   * Get timings
   * @return timings
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getTimings() {
    return timings;
  }


  public void setTimings(Object timings) {
    this.timings = timings;
  }


  public Entry serverIPAddress(String serverIPAddress) {
    
    this.serverIPAddress = serverIPAddress;
    return this;
  }

   /**
   * Get serverIPAddress
   * @return serverIPAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServerIPAddress() {
    return serverIPAddress;
  }


  public void setServerIPAddress(String serverIPAddress) {
    this.serverIPAddress = serverIPAddress;
  }


  public Entry webSocketMessages(List<WebSocketMessage> webSocketMessages) {
    
    this.webSocketMessages = webSocketMessages;
    return this;
  }

  public Entry addWebSocketMessagesItem(WebSocketMessage webSocketMessagesItem) {
    if (this.webSocketMessages == null) {
      this.webSocketMessages = new ArrayList<WebSocketMessage>();
    }
    this.webSocketMessages.add(webSocketMessagesItem);
    return this;
  }

   /**
   * Get webSocketMessages
   * @return webSocketMessages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WebSocketMessage> getWebSocketMessages() {
    return webSocketMessages;
  }


  public void setWebSocketMessages(List<WebSocketMessage> webSocketMessages) {
    this.webSocketMessages = webSocketMessages;
  }


  public Entry connection(String connection) {
    
    this.connection = connection;
    return this;
  }

   /**
   * Get connection
   * @return connection
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getConnection() {
    return connection;
  }


  public void setConnection(String connection) {
    this.connection = connection;
  }


  public Entry comment(String comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    this.comment = comment;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entry entry = (Entry) o;
    return Objects.equals(this.pageref, entry.pageref) &&
        Objects.equals(this.startedDateTime, entry.startedDateTime) &&
        Objects.equals(this.time, entry.time) &&
        Objects.equals(this.request, entry.request) &&
        Objects.equals(this.response, entry.response) &&
        Objects.equals(this.cache, entry.cache) &&
        Objects.equals(this.timings, entry.timings) &&
        Objects.equals(this.serverIPAddress, entry.serverIPAddress) &&
        Objects.equals(this.webSocketMessages, entry.webSocketMessages) &&
        Objects.equals(this.connection, entry.connection) &&
        Objects.equals(this.comment, entry.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageref, startedDateTime, time, request, response, cache, timings, serverIPAddress, webSocketMessages, connection, comment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entry {\n");
    sb.append("    pageref: ").append(toIndentedString(pageref)).append("\n");
    sb.append("    startedDateTime: ").append(toIndentedString(startedDateTime)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    cache: ").append(toIndentedString(cache)).append("\n");
    sb.append("    timings: ").append(toIndentedString(timings)).append("\n");
    sb.append("    serverIPAddress: ").append(toIndentedString(serverIPAddress)).append("\n");
    sb.append("    webSocketMessages: ").append(toIndentedString(webSocketMessages)).append("\n");
    sb.append("    connection: ").append(toIndentedString(connection)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

