=begin
#BrowserUp MitmProxy

#___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___ 

The version of the OpenAPI document: 1.24

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'date'
require 'time'

module BrowserupMitmProxy
  class HarEntryTimings
    attr_accessor :dns

    attr_accessor :connect

    attr_accessor :blocked

    attr_accessor :_send

    attr_accessor :wait

    attr_accessor :receive

    attr_accessor :ssl

    attr_accessor :comment

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'dns' => :'dns',
        :'connect' => :'connect',
        :'blocked' => :'blocked',
        :'_send' => :'send',
        :'wait' => :'wait',
        :'receive' => :'receive',
        :'ssl' => :'ssl',
        :'comment' => :'comment'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'dns' => :'Integer',
        :'connect' => :'Integer',
        :'blocked' => :'Integer',
        :'_send' => :'Integer',
        :'wait' => :'Integer',
        :'receive' => :'Integer',
        :'ssl' => :'Integer',
        :'comment' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BrowserupMitmProxy::HarEntryTimings` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BrowserupMitmProxy::HarEntryTimings`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'dns')
        self.dns = attributes[:'dns']
      else
        self.dns = -1
      end

      if attributes.key?(:'connect')
        self.connect = attributes[:'connect']
      else
        self.connect = -1
      end

      if attributes.key?(:'blocked')
        self.blocked = attributes[:'blocked']
      else
        self.blocked = -1
      end

      if attributes.key?(:'_send')
        self._send = attributes[:'_send']
      else
        self._send = -1
      end

      if attributes.key?(:'wait')
        self.wait = attributes[:'wait']
      else
        self.wait = -1
      end

      if attributes.key?(:'receive')
        self.receive = attributes[:'receive']
      else
        self.receive = -1
      end

      if attributes.key?(:'ssl')
        self.ssl = attributes[:'ssl']
      else
        self.ssl = -1
      end

      if attributes.key?(:'comment')
        self.comment = attributes[:'comment']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @dns.nil?
        invalid_properties.push('invalid value for "dns", dns cannot be nil.')
      end

      if @dns < -1
        invalid_properties.push('invalid value for "dns", must be greater than or equal to -1.')
      end

      if @connect.nil?
        invalid_properties.push('invalid value for "connect", connect cannot be nil.')
      end

      if @connect < -1
        invalid_properties.push('invalid value for "connect", must be greater than or equal to -1.')
      end

      if @blocked.nil?
        invalid_properties.push('invalid value for "blocked", blocked cannot be nil.')
      end

      if @blocked < -1
        invalid_properties.push('invalid value for "blocked", must be greater than or equal to -1.')
      end

      if @_send.nil?
        invalid_properties.push('invalid value for "_send", _send cannot be nil.')
      end

      if @_send < -1
        invalid_properties.push('invalid value for "_send", must be greater than or equal to -1.')
      end

      if @wait.nil?
        invalid_properties.push('invalid value for "wait", wait cannot be nil.')
      end

      if @wait < -1
        invalid_properties.push('invalid value for "wait", must be greater than or equal to -1.')
      end

      if @receive.nil?
        invalid_properties.push('invalid value for "receive", receive cannot be nil.')
      end

      if @receive < -1
        invalid_properties.push('invalid value for "receive", must be greater than or equal to -1.')
      end

      if @ssl.nil?
        invalid_properties.push('invalid value for "ssl", ssl cannot be nil.')
      end

      if @ssl < -1
        invalid_properties.push('invalid value for "ssl", must be greater than or equal to -1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @dns.nil?
      return false if @dns < -1
      return false if @connect.nil?
      return false if @connect < -1
      return false if @blocked.nil?
      return false if @blocked < -1
      return false if @_send.nil?
      return false if @_send < -1
      return false if @wait.nil?
      return false if @wait < -1
      return false if @receive.nil?
      return false if @receive < -1
      return false if @ssl.nil?
      return false if @ssl < -1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] dns Value to be assigned
    def dns=(dns)
      if dns.nil?
        fail ArgumentError, 'dns cannot be nil'
      end

      if dns < -1
        fail ArgumentError, 'invalid value for "dns", must be greater than or equal to -1.'
      end

      @dns = dns
    end

    # Custom attribute writer method with validation
    # @param [Object] connect Value to be assigned
    def connect=(connect)
      if connect.nil?
        fail ArgumentError, 'connect cannot be nil'
      end

      if connect < -1
        fail ArgumentError, 'invalid value for "connect", must be greater than or equal to -1.'
      end

      @connect = connect
    end

    # Custom attribute writer method with validation
    # @param [Object] blocked Value to be assigned
    def blocked=(blocked)
      if blocked.nil?
        fail ArgumentError, 'blocked cannot be nil'
      end

      if blocked < -1
        fail ArgumentError, 'invalid value for "blocked", must be greater than or equal to -1.'
      end

      @blocked = blocked
    end

    # Custom attribute writer method with validation
    # @param [Object] _send Value to be assigned
    def _send=(_send)
      if _send.nil?
        fail ArgumentError, '_send cannot be nil'
      end

      if _send < -1
        fail ArgumentError, 'invalid value for "_send", must be greater than or equal to -1.'
      end

      @_send = _send
    end

    # Custom attribute writer method with validation
    # @param [Object] wait Value to be assigned
    def wait=(wait)
      if wait.nil?
        fail ArgumentError, 'wait cannot be nil'
      end

      if wait < -1
        fail ArgumentError, 'invalid value for "wait", must be greater than or equal to -1.'
      end

      @wait = wait
    end

    # Custom attribute writer method with validation
    # @param [Object] receive Value to be assigned
    def receive=(receive)
      if receive.nil?
        fail ArgumentError, 'receive cannot be nil'
      end

      if receive < -1
        fail ArgumentError, 'invalid value for "receive", must be greater than or equal to -1.'
      end

      @receive = receive
    end

    # Custom attribute writer method with validation
    # @param [Object] ssl Value to be assigned
    def ssl=(ssl)
      if ssl.nil?
        fail ArgumentError, 'ssl cannot be nil'
      end

      if ssl < -1
        fail ArgumentError, 'invalid value for "ssl", must be greater than or equal to -1.'
      end

      @ssl = ssl
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          dns == o.dns &&
          connect == o.connect &&
          blocked == o.blocked &&
          _send == o._send &&
          wait == o.wait &&
          receive == o.receive &&
          ssl == o.ssl &&
          comment == o.comment
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [dns, connect, blocked, _send, wait, receive, ssl, comment].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = BrowserupMitmProxy.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
