"""
    BrowserUp Proxy

    ___ This is the REST API for controlling the BrowserUp Proxy. The BrowserUp Proxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import BrowserUpMitmProxyClient
from BrowserUpMitmProxyClient.model.entry_request import EntryRequest
from BrowserUpMitmProxyClient.model.entry_response import EntryResponse
from BrowserUpMitmProxyClient.model.entry_timings import EntryTimings
from BrowserUpMitmProxyClient.model.web_socket_message import WebSocketMessage
globals()['EntryRequest'] = EntryRequest
globals()['EntryResponse'] = EntryResponse
globals()['EntryTimings'] = EntryTimings
globals()['WebSocketMessage'] = WebSocketMessage
from BrowserUpMitmProxyClient.model.entry import Entry


class TestEntry(unittest.TestCase):
    """Entry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntry(self):
        """Test Entry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Entry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
