# coding: utf-8

"""
BrowserUp MitmProxy

___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___

The version of the OpenAPI document: 1.0.0
Contact: developers@browserup.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestHarEntryResponseContent(unittest.TestCase):
    """HarEntryResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test HarEntryResponseContent
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `HarEntryResponseContent`
        """
        model = BrowserUpMitmProxyClient.models.har_entry_response_content.HarEntryResponseContent()  # noqa: E501
        if include_optional :
            return HarEntryResponseContent(
                size = 56, 
                compression = 56, 
                mime_type = '', 
                text = '', 
                encoding = '', 
                comment = ''
            )
        else :
            return HarEntryResponseContent(
                size = 56,
                mime_type = '',
        )
        """

    def testHarEntryResponseContent(self):
        """Test HarEntryResponseContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
