"""
    BrowserUp Proxy

    ___ This is the REST API for controlling the BrowserUp Proxy. The BrowserUp Proxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import BrowserUpMitmProxyClient
from BrowserUpMitmProxyClient.model.entry import Entry
from BrowserUpMitmProxyClient.model.har_log_creator import HarLogCreator
from BrowserUpMitmProxyClient.model.page import Page
globals()['Entry'] = Entry
globals()['HarLogCreator'] = HarLogCreator
globals()['Page'] = Page
from BrowserUpMitmProxyClient.model.har_log import HarLog


class TestHarLog(unittest.TestCase):
    """HarLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHarLog(self):
        """Test HarLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HarLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
