/*
 * BrowserUp MitmProxy
 * ___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___ 
 *
 * The version of the OpenAPI document: 1.24
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.browserup.proxy_client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HarEntryTimings
 */
public class HarEntryTimingsTest {
    private final HarEntryTimings model = new HarEntryTimings();

    /**
     * Model tests for HarEntryTimings
     */
    @Test
    public void testHarEntryTimings() {
        // TODO: test HarEntryTimings
    }

    /**
     * Test the property 'dns'
     */
    @Test
    public void dnsTest() {
        // TODO: test dns
    }

    /**
     * Test the property 'connect'
     */
    @Test
    public void connectTest() {
        // TODO: test connect
    }

    /**
     * Test the property 'blocked'
     */
    @Test
    public void blockedTest() {
        // TODO: test blocked
    }

    /**
     * Test the property 'send'
     */
    @Test
    public void sendTest() {
        // TODO: test send
    }

    /**
     * Test the property 'wait'
     */
    @Test
    public void waitTest() {
        // TODO: test wait
    }

    /**
     * Test the property 'receive'
     */
    @Test
    public void receiveTest() {
        // TODO: test receive
    }

    /**
     * Test the property 'ssl'
     */
    @Test
    public void sslTest() {
        // TODO: test ssl
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

}
