/*
 * BrowserUp Proxy
 * ___ This is the REST API for controlling the BrowserUp Proxy.  The BrowserUp Proxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___ 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.browserup.proxy_client;

import com.browserup.proxy_client.NameValuePair;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MatchCriteria
 */
public class MatchCriteriaTest {
    private final MatchCriteria model = new MatchCriteria();

    /**
     * Model tests for MatchCriteria
     */
    @Test
    public void testMatchCriteria() {
        // TODO: test MatchCriteria
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'websocketMessage'
     */
    @Test
    public void websocketMessageTest() {
        // TODO: test websocketMessage
    }

    /**
     * Test the property 'requestHeader'
     */
    @Test
    public void requestHeaderTest() {
        // TODO: test requestHeader
    }

    /**
     * Test the property 'requestCookie'
     */
    @Test
    public void requestCookieTest() {
        // TODO: test requestCookie
    }

    /**
     * Test the property 'responseHeader'
     */
    @Test
    public void responseHeaderTest() {
        // TODO: test responseHeader
    }

    /**
     * Test the property 'responseCookie'
     */
    @Test
    public void responseCookieTest() {
        // TODO: test responseCookie
    }

    /**
     * Test the property 'jsonValid'
     */
    @Test
    public void jsonValidTest() {
        // TODO: test jsonValid
    }

    /**
     * Test the property 'jsonPath'
     */
    @Test
    public void jsonPathTest() {
        // TODO: test jsonPath
    }

    /**
     * Test the property 'jsonSchema'
     */
    @Test
    public void jsonSchemaTest() {
        // TODO: test jsonSchema
    }

}
