/*
 * BrowserUp Proxy
 * ___ This is the REST API for controlling the BrowserUp Proxy.  The BrowserUp Proxy is a swiss army knife for automated testing. It allows traffic capture in HAR files and manipulation.  It is also useful for Selenium/Cypress tests. ___ 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.browserup.proxy_client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PagePageTimings
 */
public class PagePageTimingsTest {
    private final PagePageTimings model = new PagePageTimings();

    /**
     * Model tests for PagePageTimings
     */
    @Test
    public void testPagePageTimings() {
        // TODO: test PagePageTimings
    }

    /**
     * Test the property 'onContentLoad'
     */
    @Test
    public void onContentLoadTest() {
        // TODO: test onContentLoad
    }

    /**
     * Test the property 'onLoad'
     */
    @Test
    public void onLoadTest() {
        // TODO: test onLoad
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

}
