# flake8: noqa

"""
    BrowserUp MitmProxy

    ___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: developers@browserup.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from BrowserUpMitmProxyClient.api_client import ApiClient

# import Configuration
from BrowserUpMitmProxyClient.configuration import Configuration

# import exceptions
from BrowserUpMitmProxyClient.exceptions import OpenApiException
from BrowserUpMitmProxyClient.exceptions import ApiAttributeError
from BrowserUpMitmProxyClient.exceptions import ApiTypeError
from BrowserUpMitmProxyClient.exceptions import ApiValueError
from BrowserUpMitmProxyClient.exceptions import ApiKeyError
from BrowserUpMitmProxyClient.exceptions import ApiException
