#!/usr/bin/env python
#
# Simple script showing how to read a mitmproxy dump file
#

from libmproxy import flow
import json, sys

with open("logfile", "rb") as logfile:
    freader = flow.FlowReader(logfile)
    try:
        for f in freader.stream():
            print(f)
            print(f.request.host)
            json.dump(f.get_state(), sys.stdout, indent=4)
            print ""
    except flow.FlowReadError, v:
        print "Flow file corrupted. Stopped loading."
