#!/usr/bin/env python
#
# Simple script showing how to read a mitmproxy dump file
#

from libmproxy import flow
import json
import pprint
import sys

with open(sys.argv[1], "rb") as logfile:
    freader = flow.FlowReader(logfile)
    try:
        for f in freader.stream():
            print(f)
            print(f.request.host)
            pprint.PrettyPrinter( indent=4 ).pprint( state )
            print("")
    except flow.FlowReadError as v:
        print "Flow file corrupted. Stopped loading."
