#!/bin/sh

# Quick and dangerous script for building OSX binaries.

# A few quirks to note, which should be re-checked every release:
# - We require the latest development version of PyInstaller.
 
# - PyInstaller has trouble detecting the zope.interfaces package. This is
# required by Twisted, which for mysterious reasons is required by Urwid. The
# answer is to touch the __init__.py file in the zope directory. On my system:
#   touch /Library/Python/2.7/site-packages/zope/__init__.py

# To run, change into the pyinstaller directory, and then run this script.

DST=/tmp/osx-mitmproxy
MITMPROXY=~/mitmproxy/mitmproxy
PYINST_CMD="./pyinstaller.py -F --clean"

rm -rf $DST
mkdir -p $DST
rm -rf mitmproxy
rm -rf mitmdump

$PYINST_CMD $MITMPROXY/mitmproxy
cp mitmproxy/dist/mitmproxy $DST

$PYINST_CMD $MITMPROXY/mitmdump
cp mitmdump/dist/mitmdump $DST

cshape $MITMPROXY/doc-src $DST/doc
