#!/bin/sh

# Quick and dangerous script for building OSX binaries.

# First, have a recent checkout of the dev version of pyinstaller. Change into
# the pyinstaller directory, and then run this script.

mkdir -p /tmp/osx-mitmproxy
rm -rf mitmproxy
rm -rf mitmdump

./pyinstaller.py -F ~/mitmproxy/mitmproxy/mitmproxy
cp mitmproxy/dist/mitmproxy /tmp/osx-mitmproxy

./pyinstaller.py -F ~/mitmproxy/mitmproxy/mitmdump
cp mitmdump/dist/mitmdump /tmp/osx-mitmproxy
