#!/bin/bash

MITMPROXY_DIR=~/mitmproxy/mitmproxy
NETLIB_DIR=~/mitmproxy/netlib
PATHOD_DIR=~/mitmproxy/pathod
DST=/tmp/mitmproxy_release

rm -rf $DST
mkdir -p $DST

cd $NETLIB_DIR
echo "Creating netlib source distribution..."
python ./setup.py -q sdist --dist-dir $DST

echo "Creating mitmproxy source distribution..."
cd $MITMPROXY_DIR
python ./setup.py -q sdist --dist-dir $DST

echo "Creating pathod source distribution..."
cd $PATHOD_DIR
python ./setup.py -q sdist --dist-dir $DST

echo "Creating virtualenv for test install..."
virtualenv -q $DST/venv

cd $DST
echo "Installing netlib..."
./venv/bin/pip -q install --download-cache ~/.pipcache ./netlib*
echo "Installing pathod..."
./venv/bin/pip -q install --download-cache ~/.pipcache ./pathod*
echo "Installing mitmproxy..."
./venv/bin/pip -q install --download-cache ~/.pipcache ./mitmproxy*

echo "Running binaries..."
./venv/bin/mitmproxy --version
./venv/bin/mitmdump --version
./venv/bin/pathod --version
./venv/bin/pathoc --version
