#!/usr/bin/env bash

set -e

for script in scripts/* ; do
  echo "Generating output for $script ..."
  output="${script##*/}"
  "$script" > "src/generated/${output%.*}.html"
done

python3 render_examples > src/content/addons-examples.md

cd src
hugo
