#!/bin/bash

# This script gets run from CI to render and upload docs

./build

# Only upload if we have defined credentials - we only have these defined for
# trusted commits (i.e. not PRs).
if [[ ! -z "${AWS_ACCESS_KEY_ID}" && $TRAVIS_BRANCH == "master" ]]; then
    aws s3 sync --acl public-read ./public s3://docs.mitmproxy.org/master
    # aws cloudfront create-invalidation --distribution-id E3UCZ4MLN4TO7U \
    #     --paths "/master"
fi
