/**
 * BrowserUp MitmProxy
 * ___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___ 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HarEntryCache from './HarEntryCache';
import HarEntryRequest from './HarEntryRequest';
import HarEntryResponse from './HarEntryResponse';
import HarEntryTimings from './HarEntryTimings';

/**
 * The HarEntry model module.
 * @module BrowserUpMitmProxyClient/model/HarEntry
 * @version 1.0.0
 */
class HarEntry {
    /**
     * Constructs a new <code>HarEntry</code>.
     * @alias module:BrowserUpMitmProxyClient/model/HarEntry
     * @param startedDateTime {Object} 
     * @param time {Object} 
     * @param request {module:BrowserUpMitmProxyClient/model/HarEntryRequest} 
     * @param response {module:BrowserUpMitmProxyClient/model/HarEntryResponse} 
     * @param cache {module:BrowserUpMitmProxyClient/model/HarEntryCache} 
     * @param timings {module:BrowserUpMitmProxyClient/model/HarEntryTimings} 
     */
    constructor(startedDateTime, time, request, response, cache, timings) { 
        
        HarEntry.initialize(this, startedDateTime, time, request, response, cache, timings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startedDateTime, time, request, response, cache, timings) { 
        obj['startedDateTime'] = startedDateTime;
        obj['time'] = time;
        obj['request'] = request;
        obj['response'] = response;
        obj['cache'] = cache;
        obj['timings'] = timings;
    }

    /**
     * Constructs a <code>HarEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:BrowserUpMitmProxyClient/model/HarEntry} obj Optional instance to populate.
     * @return {module:BrowserUpMitmProxyClient/model/HarEntry} The populated <code>HarEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HarEntry();

            if (data.hasOwnProperty('pageref')) {
                obj['pageref'] = ApiClient.convertToType(data['pageref'], Object);
            }
            if (data.hasOwnProperty('startedDateTime')) {
                obj['startedDateTime'] = ApiClient.convertToType(data['startedDateTime'], Object);
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], Object);
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = HarEntryRequest.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('response')) {
                obj['response'] = HarEntryResponse.constructFromObject(data['response']);
            }
            if (data.hasOwnProperty('cache')) {
                obj['cache'] = HarEntryCache.constructFromObject(data['cache']);
            }
            if (data.hasOwnProperty('timings')) {
                obj['timings'] = HarEntryTimings.constructFromObject(data['timings']);
            }
            if (data.hasOwnProperty('serverIPAddress')) {
                obj['serverIPAddress'] = ApiClient.convertToType(data['serverIPAddress'], Object);
            }
            if (data.hasOwnProperty('_webSocketMessages')) {
                obj['_webSocketMessages'] = ApiClient.convertToType(data['_webSocketMessages'], Object);
            }
            if (data.hasOwnProperty('connection')) {
                obj['connection'] = ApiClient.convertToType(data['connection'], Object);
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HarEntry</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HarEntry</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of HarEntry.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `request`
        if (data['request']) { // data not null
          HarEntryRequest.validateJSON(data['request']);
        }
        // validate the optional field `response`
        if (data['response']) { // data not null
          HarEntryResponse.validateJSON(data['response']);
        }
        // validate the optional field `cache`
        if (data['cache']) { // data not null
          HarEntryCache.validateJSON(data['cache']);
        }
        // validate the optional field `timings`
        if (data['timings']) { // data not null
          HarEntryTimings.validateJSON(data['timings']);
        }

        return true;
    }


}

HarEntry.RequiredProperties = ["startedDateTime", "time", "request", "response", "cache", "timings"];

/**
 * @member {Object} pageref
 */
HarEntry.prototype['pageref'] = undefined;

/**
 * @member {Object} startedDateTime
 */
HarEntry.prototype['startedDateTime'] = undefined;

/**
 * @member {Object} time
 */
HarEntry.prototype['time'] = undefined;

/**
 * @member {module:BrowserUpMitmProxyClient/model/HarEntryRequest} request
 */
HarEntry.prototype['request'] = undefined;

/**
 * @member {module:BrowserUpMitmProxyClient/model/HarEntryResponse} response
 */
HarEntry.prototype['response'] = undefined;

/**
 * @member {module:BrowserUpMitmProxyClient/model/HarEntryCache} cache
 */
HarEntry.prototype['cache'] = undefined;

/**
 * @member {module:BrowserUpMitmProxyClient/model/HarEntryTimings} timings
 */
HarEntry.prototype['timings'] = undefined;

/**
 * @member {Object} serverIPAddress
 */
HarEntry.prototype['serverIPAddress'] = undefined;

/**
 * @member {Object} _webSocketMessages
 */
HarEntry.prototype['_webSocketMessages'] = undefined;

/**
 * @member {Object} connection
 */
HarEntry.prototype['connection'] = undefined;

/**
 * @member {Object} comment
 */
HarEntry.prototype['comment'] = undefined;






export default HarEntry;

