/**
 * BrowserUp MitmProxy
 * ___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___ 
 *
 * The version of the OpenAPI document: 1.24
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MatchCriteriaRequestHeader from './MatchCriteriaRequestHeader';

/**
 * The MatchCriteria model module.
 * @module BrowserUpMitmProxyClient/model/MatchCriteria
 * @version 1.0.0
 */
class MatchCriteria {
    /**
     * Constructs a new <code>MatchCriteria</code>.
     * A set of criteria for filtering HTTP Requests and Responses.                          Criteria are AND based, and use python regular expressions for string comparison
     * @alias module:BrowserUpMitmProxyClient/model/MatchCriteria
     */
    constructor() { 
        
        MatchCriteria.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MatchCriteria</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:BrowserUpMitmProxyClient/model/MatchCriteria} obj Optional instance to populate.
     * @return {module:BrowserUpMitmProxyClient/model/MatchCriteria} The populated <code>MatchCriteria</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchCriteria();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('websocket_message')) {
                obj['websocket_message'] = ApiClient.convertToType(data['websocket_message'], 'String');
            }
            if (data.hasOwnProperty('request_header')) {
                obj['request_header'] = MatchCriteriaRequestHeader.constructFromObject(data['request_header']);
            }
            if (data.hasOwnProperty('request_cookie')) {
                obj['request_cookie'] = MatchCriteriaRequestHeader.constructFromObject(data['request_cookie']);
            }
            if (data.hasOwnProperty('response_header')) {
                obj['response_header'] = MatchCriteriaRequestHeader.constructFromObject(data['response_header']);
            }
            if (data.hasOwnProperty('response_cookie')) {
                obj['response_cookie'] = MatchCriteriaRequestHeader.constructFromObject(data['response_cookie']);
            }
            if (data.hasOwnProperty('json_valid')) {
                obj['json_valid'] = ApiClient.convertToType(data['json_valid'], 'Boolean');
            }
            if (data.hasOwnProperty('json_path')) {
                obj['json_path'] = ApiClient.convertToType(data['json_path'], 'String');
            }
            if (data.hasOwnProperty('json_schema')) {
                obj['json_schema'] = ApiClient.convertToType(data['json_schema'], 'String');
            }
            if (data.hasOwnProperty('error_if_no_traffic')) {
                obj['error_if_no_traffic'] = ApiClient.convertToType(data['error_if_no_traffic'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchCriteria</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchCriteria</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['page'] && !(typeof data['page'] === 'string' || data['page'] instanceof String)) {
            throw new Error("Expected the field `page` to be a primitive type in the JSON string but got " + data['page']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['content_type'] && !(typeof data['content_type'] === 'string' || data['content_type'] instanceof String)) {
            throw new Error("Expected the field `content_type` to be a primitive type in the JSON string but got " + data['content_type']);
        }
        // ensure the json data is a string
        if (data['websocket_message'] && !(typeof data['websocket_message'] === 'string' || data['websocket_message'] instanceof String)) {
            throw new Error("Expected the field `websocket_message` to be a primitive type in the JSON string but got " + data['websocket_message']);
        }
        // validate the optional field `request_header`
        if (data['request_header']) { // data not null
          MatchCriteriaRequestHeader.validateJSON(data['request_header']);
        }
        // validate the optional field `request_cookie`
        if (data['request_cookie']) { // data not null
          MatchCriteriaRequestHeader.validateJSON(data['request_cookie']);
        }
        // validate the optional field `response_header`
        if (data['response_header']) { // data not null
          MatchCriteriaRequestHeader.validateJSON(data['response_header']);
        }
        // validate the optional field `response_cookie`
        if (data['response_cookie']) { // data not null
          MatchCriteriaRequestHeader.validateJSON(data['response_cookie']);
        }
        // ensure the json data is a string
        if (data['json_path'] && !(typeof data['json_path'] === 'string' || data['json_path'] instanceof String)) {
            throw new Error("Expected the field `json_path` to be a primitive type in the JSON string but got " + data['json_path']);
        }
        // ensure the json data is a string
        if (data['json_schema'] && !(typeof data['json_schema'] === 'string' || data['json_schema'] instanceof String)) {
            throw new Error("Expected the field `json_schema` to be a primitive type in the JSON string but got " + data['json_schema']);
        }

        return true;
    }


}



/**
 * Request URL regexp to match
 * @member {String} url
 */
MatchCriteria.prototype['url'] = undefined;

/**
 * current|all
 * @member {String} page
 */
MatchCriteria.prototype['page'] = undefined;

/**
 * HTTP Status code to match.
 * @member {String} status
 */
MatchCriteria.prototype['status'] = undefined;

/**
 * Body content regexp content to match
 * @member {String} content
 */
MatchCriteria.prototype['content'] = undefined;

/**
 * Content type
 * @member {String} content_type
 */
MatchCriteria.prototype['content_type'] = undefined;

/**
 * Websocket message text to match
 * @member {String} websocket_message
 */
MatchCriteria.prototype['websocket_message'] = undefined;

/**
 * @member {module:BrowserUpMitmProxyClient/model/MatchCriteriaRequestHeader} request_header
 */
MatchCriteria.prototype['request_header'] = undefined;

/**
 * @member {module:BrowserUpMitmProxyClient/model/MatchCriteriaRequestHeader} request_cookie
 */
MatchCriteria.prototype['request_cookie'] = undefined;

/**
 * @member {module:BrowserUpMitmProxyClient/model/MatchCriteriaRequestHeader} response_header
 */
MatchCriteria.prototype['response_header'] = undefined;

/**
 * @member {module:BrowserUpMitmProxyClient/model/MatchCriteriaRequestHeader} response_cookie
 */
MatchCriteria.prototype['response_cookie'] = undefined;

/**
 * Is valid JSON
 * @member {Boolean} json_valid
 */
MatchCriteria.prototype['json_valid'] = undefined;

/**
 * Has JSON path
 * @member {String} json_path
 */
MatchCriteria.prototype['json_path'] = undefined;

/**
 * Validates against passed JSON schema
 * @member {String} json_schema
 */
MatchCriteria.prototype['json_schema'] = undefined;

/**
 * If the proxy has NO traffic at all, return error
 * @member {Boolean} error_if_no_traffic
 * @default true
 */
MatchCriteria.prototype['error_if_no_traffic'] = true;






export default MatchCriteria;

