#!/bin/bash

# Generate a test pattern with pathoc
PATHOD=http://localhost:9999
pathoc localhost:8080 "get:'$PATHOD/p/200:p0,1:b@200b':b@200b"
pathoc localhost:8080 "get:'$PATHOD/p/300:p0,1:b@200b':b@200b"
pathoc localhost:8080 "get:'$PATHOD/p/400:p0,1:b@200b':b@200b"
pathoc localhost:8080 "get:'$PATHOD/p/500:p0,1:b@200b':b@200b"
pathoc localhost:8080 "get:'$PATHOD/p/600:p0,1:b@200b':b@200b"
