name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: mhils/workflows/checkout@8fe88b311a66c441e01edfebe4cd90d8a47fa335
      - uses: mhils/workflows/setup-uv@8fe88b311a66c441e01edfebe4cd90d8a47fa335

      - run: uv lock

      - uses: mhils/workflows/uv-sync@8fe88b311a66c441e01edfebe4cd90d8a47fa335

      - run: ruff check --fix-only .
      - run: ruff format .

      - run: web/gen/all

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .github/node-version.txt
      - run: npm ci
        working-directory: web
      - run: npm run eslint
        working-directory: web
        continue-on-error: true
      - run: npm run prettier
        working-directory: web

      - uses: mhils/add-pr-ref-in-changelog@6df8cd5a0c4d0a8c0353b663153d4a36384054f4 # main

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
