name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (major.minor.patch)'
        required: true
        type: string
      skip-branch-status-check:
        description: 'Skip CI status check.'
        default: false
        required: false
        type: boolean

permissions:
  actions: write
  contents: write

jobs:
  release:
    environment: deploy-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GH_PUSH_TOKEN }}  # this token works to push to the protected main branch.
          persist-credentials: true
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .github/node-version.txt
      - uses: mhils/workflows/setup-python@acc73c7af100db9fb3f1ad3c0178d382048e943f
      - run: ./release/release.py ${{ inputs.version }} ${{ inputs.skip-branch-status-check }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # this token works with the GraphQL API
