name: Running Synopsys Scans
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  blackduck:
    uses: projectxyzio/gh-actions/.github/workflows/blackduck.yml@master
    with:
      blackduck-project-name: "mitmproxy"
      blackduck-project-group-name: "HeadSpin Codebase"
      blackduck-project-tags: "deployed,fork,python"
    secrets: inherit
